# PEP 621 standardized project metadata. This is the modern, preferred way
# to declare core information for tools like pip and build.
[project]
name = "adf1-framework"
version = "0.1.0"
description = "Your short package description"
authors = [
    { name = "Basil Example", email = "basil@example.com" }
]
dependencies = [
    # Dependencies from the [tool.poetry.dependencies] section would be mirrored here.
    # e.g., "fastapi>=0.100.0"
]
requires-python = ">=3.13"


# Defines project metadata, dependencies, and scripts using the Poetry tool.
# This section is kept for backward compatibility.
[tool.poetry]
name = "adf1-framework"
version = "0.1.0"
description = ""
authors = ["Basil <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.13"
# Other dependencies would be listed here as well.

# Declares the build system for PEP 517 compatibility.
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Configures the Ruff linter and formatter for code quality and consistency.
[tool.ruff]
line-length = 88
target-version = "py311" # Consider updating this to "py313" to match your Python version

# Configures Ruff's integrated import sorter (isort).
[tool.ruff.isort]
known_first_party = [
    "core",
    "orchestrator",
    "services",
    "api",
    "security",
    "utils"
]
combine_as_imports = true
force_sort_within_sections = true

# Application-specific settings for the Translation App, controlled by a feature flag.
[tool.translation_app]
enabled = false
version = "0.1.0"
capabilities = ["get_supported_languages", "translate"]