name: Document Automation

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'core/**'

jobs:
  build-and-document:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add your dependency installation command here
        pip install -r requirements.txt

    - name: Run Orchestrator for Doc Generation
      run: |
        # This command runs your orchestrator, which is expected to
        # generate logs in the orchestrator_artifacts/ directory.
        python -m core.orchestrator --plan instructions/doc-generation-plan.json

    # PATCH APPLIED HERE
    # Upload orchestrator step logs for debugging and analysis
    - name: Upload step logs
      uses: actions/upload-artifact@v4
      with:
        name: orchestrator-step-logs
        path: orchestrator_artifacts/
        retention-days: 30
        if-no-files-found: warn

    - name: Auto-label PR for documentation changes
      # This is the existing step that the patch was placed before
      if: github.event_name == 'pull_request'
      run: echo "PR auto-labeling logic for docs would run here..."